"""add window model

Revision ID: 01f220560966
Revises: 7a8745d11968
Create Date: 2022-10-12 20:14:26.201883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f220560966'
down_revision = '7a8745d11968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction', sa.Column('shgc', sa.Float(), nullable=True))
    op.add_column('construction', sa.Column('vt', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('solarAbsorptance', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('solarTransmittance', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('interiorEmissivity', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('exteriorEmissivity', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('interiorCoefficientOfCavityConvection', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('exteriorCoefficientOfCavityConvection', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('velocityOfAirFlowThroughCavity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'velocityOfAirFlowThroughCavity')
    op.drop_column('material', 'exteriorCoefficientOfCavityConvection')
    op.drop_column('material', 'interiorCoefficientOfCavityConvection')
    op.drop_column('material', 'exteriorEmissivity')
    op.drop_column('material', 'interiorEmissivity')
    op.drop_column('material', 'solarTransmittance')
    op.drop_column('material', 'solarAbsorptance')
    op.drop_column('construction', 'vt')
    op.drop_column('construction', 'shgc')
    # ### end Alembic commands ###
