"""empty message

Revision ID: 0c2a0a34cb95
Revises: fb536a0c77c1
Create Date: 2022-07-25 16:21:52.170387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2a0a34cb95'
down_revision = 'fb536a0c77c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction', sa.Column('categories', sa.String(length=255), nullable=False))
    op.drop_column('material', 'constructionId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('constructionId', sa.INTEGER(), nullable=True))
    op.drop_column('construction', 'categories')
    # ### end Alembic commands ###
