"""empty message

Revision ID: 167b6046cc37
Revises: 
Create Date: 2022-07-26 08:46:56.519857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167b6046cc37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('categories', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('conductivity', sa.Float(), nullable=False),
    sa.Column('specificHeat', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('moistureConductivity', sa.Float(), nullable=False),
    sa.Column('moistureCapacity', sa.Float(), nullable=False),
    sa.Column('constructionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructionId'], ['construction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('constructionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructionId'], ['construction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('material')
    op.drop_table('construction')
    # ### end Alembic commands ###
