"""empty message

Revision ID: 2c6b7dc85f77
Revises: 0df16a27d710
Create Date: 2022-08-18 15:20:22.081322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6b7dc85f77'
down_revision = '0df16a27d710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('classification', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'classification')
    # ### end Alembic commands ###
