"""empty message

Revision ID: 93e040f8772d
Revises: 9e4e57f46b3e
Create Date: 2022-09-11 10:25:13.391967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e040f8772d'
down_revision = '9e4e57f46b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'monthlySch', 'schedule', ['scheduleId'], ['id'])
    op.add_column('weeklySch', sa.Column('scheduleId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'weeklySch', 'schedule', ['scheduleId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weeklySch', type_='foreignkey')
    op.drop_column('weeklySch', 'scheduleId')
    op.drop_constraint(None, 'monthlySch', type_='foreignkey')
    # ### end Alembic commands ###
