"""empty message

Revision ID: 9c2a3d0587b8
Revises: 01f220560966
Create Date: 2022-10-12 20:53:26.768576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2a3d0587b8'
down_revision = '01f220560966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('thickness', sa.String(length=255), nullable=False),
    sa.Column('categories', sa.String(length=255), nullable=False),
    sa.Column('uvalue', sa.Float(), nullable=True),
    sa.Column('shgc', sa.Float(), nullable=True),
    sa.Column('vt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('window_material',
    sa.Column('windowId', sa.Integer(), nullable=True),
    sa.Column('materialId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materialId'], ['material.id'], ),
    sa.ForeignKeyConstraint(['windowId'], ['window.id'], )
    )
    op.create_table('window_tag',
    sa.Column('windowId', sa.Integer(), nullable=True),
    sa.Column('tagId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tagId'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['windowId'], ['window.id'], )
    )
    op.drop_column('construction', 'shgc')
    op.drop_column('construction', 'vt')
    op.drop_constraint(None, 'windowIdentifier', type_='foreignkey')
    op.create_foreign_key(None, 'windowIdentifier', 'window', ['windowId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'windowIdentifier', type_='foreignkey')
    op.create_foreign_key(None, 'windowIdentifier', 'construction', ['windowId'], ['id'])
    op.add_column('construction', sa.Column('vt', sa.FLOAT(), nullable=True))
    op.add_column('construction', sa.Column('shgc', sa.FLOAT(), nullable=True))
    op.drop_table('window_tag')
    op.drop_table('window_material')
    op.drop_table('window')
    # ### end Alembic commands ###
