"""empty message

Revision ID: 9e4e57f46b3e
Revises: e11dc4dbb0fb
Create Date: 2022-09-10 11:52:59.545929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4e57f46b3e'
down_revision = 'e11dc4dbb0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailySch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hvac', sa.String(length=255), nullable=False),
    sa.Column('cooling', sa.String(length=255), nullable=False),
    sa.Column('heating', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthlySch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hvac', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weeklySch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hvac', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_dailySch',
    sa.Column('scheduleId', sa.Integer(), nullable=True),
    sa.Column('dailyId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dailyId'], ['dailySch.id'], ),
    sa.ForeignKeyConstraint(['scheduleId'], ['schedule.id'], )
    )
    op.create_table('schedule_tag',
    sa.Column('scheduleId', sa.Integer(), nullable=True),
    sa.Column('tagId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheduleId'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_tag')
    op.drop_table('schedule_dailySch')
    op.drop_table('weeklySch')
    op.drop_table('schedule')
    op.drop_table('monthlySch')
    op.drop_table('dailySch')
    # ### end Alembic commands ###
