"""empty message

Revision ID: e11dc4dbb0fb
Revises: 2c6b7dc85f77
Create Date: 2022-08-24 07:25:28.104028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11dc4dbb0fb'
down_revision = '2c6b7dc85f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction', sa.Column('uvalue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('construction', 'uvalue')
    # ### end Alembic commands ###
