"""add relationship against construction

Revision ID: fb536a0c77c1
Revises: d64a3161436d
Create Date: 2022-07-25 13:04:02.526210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb536a0c77c1'
down_revision = 'd64a3161436d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('constructionId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material', 'construction', ['constructionId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_column('material', 'constructionId')
    # ### end Alembic commands ###
